version: '3'

services:
    python:
        image: python:3.6
        volumes:
            - ./app:/app
        ports:
            - 8000:8000
        command: bash -c "cd ./app && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
